	Variant (double   value) { type = Tag::t_double; u_double = value; }
	Variant (bool     value) { type = Tag::t_bool;   u_bool   = value; }
	Variant (uint8_t  value) { type = Tag::t_u8;     u_u8     = value; }
	Variant (int8_t   value) { type = Tag::t_s8;     u_s8     = value; }
	Variant (uint16_t value) { type = Tag::t_u16;    u_u16    = value; }
	Variant (int16_t  value) { type = Tag::t_s16;    u_s16    = value; }
	Variant (uint32_t value) { type = Tag::t_u32;    u_u32    = value; }
	Variant (int32_t  value) { type = Tag::t_s32;    u_s32    = value; }
	Variant (uint64_t value) { type = Tag::t_u64;    u_u64    = value; }
	Variant (int64_t  value) { type = Tag::t_s64;    u_s64    = value; }
